<a href="https://colab.research.google.com/github/marceloodr/bootcamp_grupo2/blob/main/Aula_2_Atividades_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividades NumPy

NumPy é um pacote extremamente interessante e necessário de aprender pois ele é o que está por trás de diversos pacotes mais avançados (alguns que veremos) do Pyhon. Alguns desses pacotes incluem o Pandas, Seaborn, Scikit-Learn e Tensorflow.

A seguir serão passadas algumas atividades simples para a fixação do conteúdo.

In [3]:
#Rode esse código para usar o numpy, sinta-se livre para alterá-lo.
import numpy as np

## Atividade 1

Crie um Array que vá do número 2017 até 2024. Comente qual a principal diferença de um array para uma lista? Printe o tipo do array e o tipo dos elementos do array. Transforme esse array num array bidimensional.

Desafio:
Mude o tipo dos elementos array para o que ocupe menos memória possível sem alterar os elementos do array.

In [ ]:
array1 = np.arange(2017,2025)

print(array1)
print(type(array1))
print(type(array1[0]))

[2017 2018 2019 2020 2021 2022 2023 2024]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [ ]:
array_bidi = array1.reshape(-1,1)
print(array_bidi)

[[2017]
 [2018]
 [2019]
 [2020]
 [2021]
 [2022]
 [2023]
 [2024]]


In [ ]:
array = array1.astype(np.uint16)
array

array([2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=uint16)

## Atividade 2

1.   Crie um array de números aleatórios entre 0 e 10;
2.   Defina um valor limite de 0 a 10, por exemplo, 4;
3.   Encontre os índices dos elementos maiores do que o valor limite;
4.   Acessar os valores dos elementos maiores do que o valor limite;
5.   Substitua os valores maiores que o limite por 0.



In [ ]:
array2 = np.random.randint(0,11,50)
array2

array([10,  2,  0,  8,  8,  4,  7, 10,  3,  9,  8,  6, 10,  1,  2,  2,  8,
       10,  7, 10, 10,  3,  0,  4, 10,  7,  3,  5,  9,  4,  5,  7,  1,  6,
        1,  9,  8,  3,  8, 10,  2,  0,  9,  2,  3,  9,  7,  5,  4,  9])

In [ ]:
limite = 4
bigger_index = np.where(array2 > limite)
bigger_index

(array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 20, 24, 25, 27,
        28, 30, 31, 33, 35, 36, 38, 39, 42, 45, 46, 47, 49], dtype=int64),)

In [ ]:
bigger_values = array2[bigger_index]
bigger_values

array([10,  8,  8,  7, 10,  9,  8,  6, 10,  8, 10,  7, 10, 10, 10,  7,  5,
        9,  5,  7,  6,  9,  8,  8, 10,  9,  9,  7,  5,  9])

In [ ]:
array2[array2 > limite] = 0
array2

array([0, 2, 0, 0, 0, 4, 0, 0, 3, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 3,
       0, 4, 0, 0, 3, 0, 0, 4, 0, 0, 1, 0, 1, 0, 0, 3, 0, 0, 2, 0, 0, 2,
       3, 0, 0, 0, 4, 0])

## Atividade 3

Foi adicionado uma lista para representar as vendas mensais de três empresas ao longo do ano.


1.   Transforme essa lista em Array;
2.   Calcule o valor minimo, maximo e medio da lista;
3.   Calcule a soma de cada mês e adicione uma coluna com esses resultados;
4.   Calcule a média de cada empresa (e da soma) e adicione como linha final;
5.   Remova as agregações;
6.   Separe o array em 4 arrays de trimestres.
7.   Faça as vendas esperadas para o ano seguinte. Espera-se que o primeiro trimestre terá um crescimento de 5%, 15% para o segundo trimestre, queda de 5% para o terceiro trimestre e crescimento de 20% para o último trimestre.
8. Junte esses arrays em um novo array, mantendo a separação por trimestre.

Desafio: Faça as vendas esperadas através da multiplicação do array de vendas trimestrais pelo array de crescimento. Transforme o array resultante para que ele tenha o mesmo shape do array original.

Espera-se Split, Stack, Concatenate e Delete.



In [1]:
vendas_mensais= [
    [10000, 15000, 20000],  # Janeiro
    [11000, 14000, 22000],  # Fevereiro
    [12000, 16000, 21000],  # Março
    [10500, 15500, 21500],  # Abril
    [11500, 14500, 22500],  # Maio
    [12500, 16500, 20500],  # Junho
    [13000, 17000, 19500],  # Julho
    [13500, 17500, 18500],  # Agosto
    [14000, 18000, 17500],  # Setembro
    [14500, 18500, 16500],  # Outubro
    [15000, 19000, 15500],  # Novembro
    [15500, 19500, 14500]   # Dezembro
]

In [4]:
#1
array_vendas = np.array(vendas_mensais)

In [5]:
#2
min_value = 999999
max_value = 0
for i in range(12):
  for j in range(3):
    if min_value > array_vendas[i,j]: min_value = array_vendas[i,j]
    if max_value < array_vendas[i,j]: max_value = array_vendas[i,j]

mid_value = array_vendas[int(array_vendas.shape[0]/2),
                         int(array_vendas.shape[1]/2)]
print(min_value, max_value, mid_value)

10000 22500 17000


In [7]:
#3
soma = np.array([])
for i in range(12):
  soma = np.append(soma, sum(array_vendas[i,:]))
soma = np.split(soma, 12)
array_vendas = np.concatenate((array_vendas, soma), axis=1)
array_vendas

array([[10000., 15000., 20000., 45000.],
       [11000., 14000., 22000., 47000.],
       [12000., 16000., 21000., 49000.],
       [10500., 15500., 21500., 47500.],
       [11500., 14500., 22500., 48500.],
       [12500., 16500., 20500., 49500.],
       [13000., 17000., 19500., 49500.],
       [13500., 17500., 18500., 49500.],
       [14000., 18000., 17500., 49500.],
       [14500., 18500., 16500., 49500.],
       [15000., 19000., 15500., 49500.],
       [15500., 19500., 14500., 49500.]])

In [8]:
#4
media = np.array([])
for i in range(4):
  media = np.append(media, np.mean(array_vendas[:,i]))

array_vendas = np.vstack((array_vendas, media))
array_vendas

array([[10000., 15000., 20000., 45000.],
       [11000., 14000., 22000., 47000.],
       [12000., 16000., 21000., 49000.],
       [10500., 15500., 21500., 47500.],
       [11500., 14500., 22500., 48500.],
       [12500., 16500., 20500., 49500.],
       [13000., 17000., 19500., 49500.],
       [13500., 17500., 18500., 49500.],
       [14000., 18000., 17500., 49500.],
       [14500., 18500., 16500., 49500.],
       [15000., 19000., 15500., 49500.],
       [15500., 19500., 14500., 49500.],
       [12750., 16750., 19125., 48625.]])

In [9]:
#5
array_vendas = np.delete(array_vendas, -1, 0)
array_vendas = np.delete(array_vendas, -1, 1)
array_vendas

array([[10000., 15000., 20000.],
       [11000., 14000., 22000.],
       [12000., 16000., 21000.],
       [10500., 15500., 21500.],
       [11500., 14500., 22500.],
       [12500., 16500., 20500.],
       [13000., 17000., 19500.],
       [13500., 17500., 18500.],
       [14000., 18000., 17500.],
       [14500., 18500., 16500.],
       [15000., 19000., 15500.],
       [15500., 19500., 14500.]])

In [10]:
#6
array_trimestres = np.split(array_vendas, 4)
trim_1 = array_trimestres[0]
trim_2 = array_trimestres[1]
trim_3 = array_trimestres[2]
trim_4 = array_trimestres[3]

In [11]:
#7
c1 = 1.05
c2 = 1.15
c3 = 0.95
c4 = 1.20

vendas_esperadas_trim1 = trim_1 * c1
vendas_esperadas_trim2 = trim_2 * c2
vendas_esperadas_trim3 = trim_3 * c3
vendas_esperadas_trim4 = trim_4 * c4

In [12]:
#8
vendas_esperadas = np.array([vendas_esperadas_trim1,
                             vendas_esperadas_trim2,
                             vendas_esperadas_trim3,
                             vendas_esperadas_trim4])
vendas_esperadas

array([[[10500., 15750., 21000.],
        [11550., 14700., 23100.],
        [12600., 16800., 22050.]],

       [[12075., 17825., 24725.],
        [13225., 16675., 25875.],
        [14375., 18975., 23575.]],

       [[12350., 16150., 18525.],
        [12825., 16625., 17575.],
        [13300., 17100., 16625.]],

       [[17400., 22200., 19800.],
        [18000., 22800., 18600.],
        [18600., 23400., 17400.]]])

## Atividade 4

Crie um array com o nome de todos os membros do grupo. Uilize das propriedades do Numpy para deixar todos os nomes em letras maiúsculas.

In [ ]:
nomes = np.array(['Arthur','Isabelle','Marcelo','Carem','Marina'])
nomes

array(['Arthur', 'Isabelle', 'Marcelo', 'Carem', 'Marina'], dtype='<U8')

In [ ]:
nomes_maiusculas = np.char.upper(nomes)
nomes_maiusculas

array(['ARTHUR', 'ISABELLE', 'MARCELO', 'CAREM', 'MARINA'], dtype='<U8')

## Atividade 5

Considerando manhã = 1 e tarde = 2, concatene o número do turno mais o número do grupo. Defina esse número como a seed. Crie uma sequencia de 10 números aleatorios entre 0 e 1. Calcule quantos desses são maiores que 0.5. Agora crie uma sequencia novamente. Essa sequencia é igual a primeira? Se não, crie uma sequencia "aleatória" novamente que tenha os mesmos números da primeira sequência. O que acontece se é repetido o código novamente?

In [ ]:
#concatene o número do turno mais o número do grupo.

import numpy as np
manha = np.array([1])
tarde = np.array([2])
grupo = np.array([2])

resultado = np.concatenate((manha,grupo))
print(resultado)

[1 2]


In [ ]:
import random
resultado = np.random.seed()

numeros_aleatorios = np.random.rand(10)
print(numeros_aleatorios)

[0.30618193 0.03079115 0.66344919 0.75723763 0.38335755 0.44831024
 0.39033448 0.4761527  0.93991985 0.41231552]


In [ ]:
maiores = numeros_aleatorios[numeros_aleatorios > 0.5]
quantidade = len(maiores)
print(maiores)
print(quantidade)

[0.66344919 0.75723763 0.93991985]
3


In [ ]:
sequencia = np.random.rand(10)
print(sequencia)

[0.24322389 0.53917532 0.02820947 0.83860761 0.45734924 0.17055789
 0.06846099 0.50014049 0.24152062 0.13817821]
